# Copyright (c) 2026 NightWorksIO
"""Every code a refusal may carry, and the shape of what the contract says of one.

Generated from the contract vendored in `contract/`. Do not edit: `just generate` rewrites it,
and CI fails on any difference.
"""

import typing

type RefusalCode = typing.Literal[
    "ADMIT-10",
    "ADMIT-11",
    "ADMIT-12",
    "ADMIT-4",
    "ADMIT-5",
    "ADMIT-6",
    "ADMIT-7",
    "ADMIT-8",
    "ADMIT-9",
    "ASK-1",
    "ASK-10",
    "ASK-11",
    "ASK-12",
    "ASK-13",
    "ASK-2",
    "ASK-3",
    "ASK-4",
    "ASK-5",
    "ASK-6",
    "ASK-7",
    "ASK-8",
    "ASK-9",
    "GONE-2",
    "LIFE-10",
    "MIGRATE-1",
    "PLAY-1",
    "PLAY-2",
    "PLAY-3",
    "PLAY-4",
    "PLAY-5",
    "PLAY-6",
    "PLAY-7",
    "PLAY-8",
    "PLAY-9",
    "PLUGIN-10",
    "PLUGIN-11",
    "PLUGIN-12",
    "PLUGIN-13",
    "PLUGIN-14",
    "PLUGIN-15",
    "PLUGIN-16",
    "PLUGIN-17",
    "PLUGIN-18",
    "PLUGIN-19",
    "PLUGIN-2",
    "PLUGIN-20",
    "PLUGIN-21",
    "PLUGIN-22",
    "PLUGIN-23",
    "PLUGIN-24",
    "PLUGIN-25",
    "PLUGIN-26",
    "PLUGIN-27",
    "PLUGIN-28",
    "PLUGIN-29",
    "PLUGIN-3",
    "PLUGIN-30",
    "PLUGIN-31",
    "PLUGIN-32",
    "PLUGIN-33",
    "PLUGIN-34",
    "PLUGIN-35",
    "PLUGIN-36",
    "PLUGIN-37",
    "PLUGIN-38",
    "PLUGIN-4",
    "PLUGIN-5",
    "PLUGIN-6",
    "PLUGIN-7",
    "PLUGIN-8",
    "PLUGIN-9",
    "RATE-6",
    "READ-1",
    "READ-10",
    "READ-11",
    "READ-12",
    "READ-13",
    "READ-14",
    "READ-15",
    "READ-16",
    "READ-2",
    "READ-3",
    "READ-4",
    "READ-5",
    "READ-6",
    "READ-7",
    "READ-8",
    "READ-9",
    "REPAIR-1",
    "RESTORE-11",
    "SERVE-6",
    "SERVE-7",
    "SERVE-8",
    "SPACE-6",
    "STACK-1",
    "STACK-10",
    "STACK-2",
    "STACK-3",
    "STACK-4",
    "STACK-5",
    "STACK-6",
    "STACK-7",
    "STACK-8",
    "STACK-9",
    "UPDATE-5",
    "WIRE-1",
    "WIRE-2",
    "WIRE-3",
    "WIRE-4",
    "WIRE-5",
    "WIRE-6",
    "WIRE-7",
]
"""Every code a refusal may carry."""


class ListedRefusal(typing.NamedTuple):
    """What the contract says of one refusal code."""

    name: str
    """The code's name in the core's registry."""
    status: int
    """The one status the refusal is answered with."""
    description: str
    """The registry's own line about it."""


__all__ = [
    "ListedRefusal",
    "RefusalCode",
]
